name: GritoBulk
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run
        run: |
          mkdir -p assets
          while read r; do [ -z "$r" ] && continue; f=$(basename "$r" | cut -d? -f1); echo "Downloading $f"; curl -L "$r" -o "assets/$f"; done < lista.txt
          git config user.name "bot"
          git config user.email "bot@bot.com"
          git add assets/
          git commit -m "upload"
          git push
